name: Build FreeRDP Android APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Android SDK & NDK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653

          # 确保 sdk 和 ndk 目录存在
          mkdir -p $ANDROID_SDK_ROOT/ndk

          # 下载并解压 NDK
          cd $ANDROID_SDK_ROOT
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          mv android-ndk-r25c $ANDROID_NDK_ROOT

          # 设置环境变量
          echo "ANDROID_NDK=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Setup CMake & Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Build FreeRDP
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
                -DANDROID_NATIVE_API_LEVEL=21 \
                -DANDROID_ABI=arm64-v8a \
                -DCMAKE_BUILD_TYPE=Release \
                ..
          cmake --build . --target install

      - name: Package APK
        run: |
          # 假设构建的 APK 文件位于 build 输出目录中，调整此路径根据实际情况
          cp path_to_apk_output/*.apk $HOME/
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: freerdp-apk
          path: $HOME/*.apk
