name: Build FreeRDP Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Android SDK and NDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30'
        ndk-version: '23.1.7779620'

    # Cache OpenSSL dependencies
    - name: Install OpenSSL
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev

    # Set OpenSSL environment variables
    - name: Set OpenSSL environment variables
      run: echo "OPENSSL_ROOT_DIR=/usr/local/ssl" >> $GITHUB_ENV

    # Set up the build environment
    - name: Set up environment variables
      run: |
        export OPENSSL_ROOT_DIR=/usr/local/ssl
        echo "OPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR"

    # Create the build directory
    - name: Create build directory
      run: mkdir -p build

    # Run CMake to configure the project
    - name: Run CMake to configure the project
      run: cmake -S . -B build -DANDROID_ABI=arm64-v8a -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=21

    # Build the project
    - name: Build the project
      run: cmake --build build

    # Archive APK file as build artifact
    - name: Archive APK
      uses: actions/upload-artifact@v4
      with:
        name: freeRDP-apk
        path: build/*.apk
