name: Build FreeRDP Android APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # 确保拉取所有子模块

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake unzip curl openjdk-17-jdk git
  
      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: r25c
          cmake-version: 3.22.1

      - name: Configure build
        run: |
          export ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          mkdir -p build-android
          cd build-android
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_PLATFORM=android-21 \
                -DWITH_OPENSSL=OFF \
                -DWITH_CLIENT=ON \
                -DWITH_SERVER=OFF \
                -G Ninja ..

      - name: Build FreeRDP
        run: |
          cd build-android
          ninja

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FreeRDP-Android-APK
          path: build-android/*.apk
