name: Build FreeRDP Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Android SDK and NDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30'
        ndk-version: '23.1.7779620'

    # Install dependencies, including OpenSSL
    - name: Install OpenSSL and other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libssl-dev \
          cmake \
          build-essential \
          git \
          pkg-config \
          libpthread-stubs0-dev \
          unzip

    # Set OpenSSL environment variables
    - name: Set OpenSSL environment variables
      run: |
        echo "OPENSSL_ROOT_DIR=/usr/include/openssl" >> $GITHUB_ENV
        echo "OPENSSL_LIBRARIES=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
        echo "OPENSSL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV

    # Create the build directory
    - name: Create build directory
      run: mkdir -p build

    # Run CMake to configure the project
    - name: Run CMake to configure the project
      run: cmake -S . -B build -DANDROID_ABI=arm64-v8a -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=21 -DOPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR

    # Build the project
    - name: Build the project
      run: cmake --build build

    # Archive APK file as build artifact
    - name: Archive APK
      uses: actions/upload-artifact@v4
      with:
        name: fre
