name: Build FreeRDP Android APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # 确保拉取所有子模块

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake unzip curl openjdk-17-jdk git

            - name: Setup Android SDK & NDK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          
          mkdir -p $ANDROID_SDK_ROOT/ndk  # 确保 ndk 目录存在
          
          cd $ANDROID_SDK_ROOT
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          mv android-ndk-r25c $ANDROID_NDK_ROOT  # 确保路径正确
          
          echo "ANDROID_NDK=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH


      - name: Configure build
        run: |
          mkdir -p build-android
          cd build-android
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_PLATFORM=android-21 \
                -DCMAKE_MAKE_PROGRAM=ninja \
                -DWITH_OPENSSL=OFF \
                -DWITH_CLIENT=ON \
                -DWITH_SERVER=OFF \
                -G Ninja ..

      - name: Build FreeRDP
        run: |
          cd build-android
          ninja

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FreeRDP-Android-APK
          path: build-android/*.apk
